language: cpp
script:
  - mkdir build
  - cd build
  - cmake -DBUILD_TESTS=1 .. && make && ctest -R anyterm
compiler:
  - gcc
#  - clang
before_install:
  - sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu/ quantal main universe"
  - sudo apt-get -qq update
  - sudo apt-get -qq install g++-4.7 libboost1.50-all-dev libvte-2.90-dev
  - sudo update-alternatives --quiet --install /usr/bin/gcc gcc /usr/bin/gcc-4.6 60 --slave /usr/bin/g++ g++ /usr/bin/g++-4.6
  - sudo update-alternatives --quiet --install /usr/bin/gcc gcc /usr/bin/gcc-4.7 40 --slave /usr/bin/g++ g++ /usr/bin/g++-4.7
  - sudo update-alternatives --quiet --set gcc /usr/bin/gcc-4.7
branches:
  only:
    - master

